kind: pipeline
type: docker
name: CI
 
trigger:
  event:
    - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - cd Verax_API_EF
      - cd Verax_API_EF
      - dotnet restore Verax_API_EF.sln
      - dotnet build Verax_API_EF.sln -c Release --no-restore
      - dotnet publish Verax_API_EF.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release

  - name: tests
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - cd Verax_API_EF
      - cd Verax_API_EF
      - dotnet restore Verax_API_EF.sln
      - dotnet test Verax_API_EF.sln --no-restore
    depends_on: [build]

  - name: code-inspection
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet8
    secrets: [ SECRET_SONAR_LOGIN ]
    environment:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN # Secret de Drone
      project_key: Verax_API_EF
    commands:
      - cd Verax_API_EF/
      - cd Verax_API_EF/
      - dotnet restore Verax_API_EF.sln
      - dotnet sonarscanner begin /k:$${project_key} /d:sonar.host.url=$${sonar_host} /d:sonar.coverageReportPaths="coveragereport/SonarQube.xml" /d:sonar.coverage.exclusions="Unit_Test_EF/**","API_Unit_Test/**","API_Tests_Console/**","Test_Console_EF/**","DbContextLib/Migrations/**","StubbedContextLib/**","API/Program.cs" /d:sonar.login=$${sonar_token} 
      - dotnet build Verax_API_EF.sln -c Release --no-restore
      - dotnet test Verax_API_EF.sln --logger trx --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "XPlat Code Coverage"
      - reportgenerator -reports:"**/coverage.cobertura.xml" -reporttypes:SonarQube -targetdir:"coveragereport"
      - dotnet publish Verax_API_EF.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release
      - dotnet sonarscanner end /d:sonar.login=$${sonar_token}
    when:
      branch:
        - master
      event:
        - push
        - pull_request
    depends_on: [build,tests]

    - name: docker-build-and-push
    image: plugins/docker
    settings:
      dockerfile: Verax_API_EF/Dockerfile
      context: Verax_API_EF
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/louis.laborie/sae_2a_API_EF
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD
    when:
      branch:
        - master

  - name: deploy-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/louis.laborie/sae_2a_API_EF:latest
      CONTAINERNAME: verax-api
      COMMAND: create
      OVERWRITE: true
      CODEFIRST_CLIENTDRONE_ENV_ASPNETCORE_HTTP_PORTS: 80
      ADMINS: louislaborie,tonyfages
    depends_on:
      - docker-build-and-push